language: c++
services:
  - docker

before_install:
  - echo "docker file not set yet"
#   - docker build -t yeejiac/InertiaTrader -f ./docker/Dockerfile.dev .

script:
#   - docker run yeejiac/InertiaTrader make main -- --coverage
  - echo "not done"
  
