language: c++
services:
  - DOCKER_COMPOSE_VERSION=1.4.2
  - docker


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - docker–compose –-version
  - docker build -t inertiatrader . --no-cache

script:
  - docker-compose up -d
  - docker run inertiatrader ./trader.out -- --coverage
  - 
  
