language: c++
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker build -f dockerfile.db -t mydb .
  - docker build -t inertiatrader . --no-cache

script:
  - docker run -d --rm --name mydb-container mydb
  - docker logs mydb-container
  - docker run -it --rm --link mydb-container mariadb:latest -p 3306:3306 --restart mysql -h mydb-container -uroot -pAa1234 stock -e "select * from stock.User;"
  # - docker run inertiatrader ./trader.out -- --coverage
  
