version: '2'
services:
  database:
    # image: mydb
    # container_name: mydb_container
    build: 
      context: .
      dockerfile: dockerfile.db
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 172.28.0.3
  inertiatrader:
    # image: inertiatrader
    # container_name: inertiatrader
    build: 
      context: .
    ports:
      - "1203:1203"
    command: >
      /bin/bash -c "
      sleep 15;
      ./trader.out devel;"
    depends_on:
      - database
    networks:
      vpcbr:
        ipv4_address: 172.28.0.2
  portainerservice:
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
      
volumes:
  portainer_data:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1