version: "3"
services:
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 1200:1200
    links:
      - web
    environment:
      - PARAMS=http -region=eu localdev.docker:80
    networks:
      dev_net:
        ipv4_address: 10.5.0.10