FROM centos:7

MAINTAINER yeejiac

COPY entrypoint.sh /sbin/entrypoint.sh

RUN chmod 755 /sbin/entrypoint.sh \
  && yum install -y epel-release \
  && curl -o /tmp/ngrok.tar.gz "http://files.git.oschina.net/group1/M00/07/11/PaAvDFyZwgKAM7opAK7VK6NTB802069.gz?attname=ngrok.tar.gz" \
  && tar -zxvf /tmp/ngrok.tar.gz -C /usr/local \
  && rm -rf /tmp/ngrok.tar.gz

EXPOSE 80/tcp 443/tcp 8081/tcp 8082/tcp

ENTRYPOINT ["/sbin/entrypoint.sh"]