version: "3"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Aa1234
    volumes:
      - data-volume:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql