version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/funlib
      - .:/lib
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"